### ISSUE TITLE
Isolate logging

### ISSUE THREAD

**Issue by gahag** [d-e-s-o/test-env-log#3]
As the logger is a global instance, and the test executable does not restart for each test, all tests that run after a given test where the logger has been initialized, will have the logging enabled. I would like to have only a few tests with logging enabled, but that does not work right now. Maybe we can have this improvement?

**Comment by d-e-s-o** [comment]
So what would a potential implementation look like, given that, as you said yourself, the logger setup is global?

**Comment by gahag** [comment]
I wonder if we can work some way around that, will surely need some brainstorming. Maybe we can manage the records based on the module/target/line attribute, and ignore those outside the correct tests, but I think that would only work for logging directly from the test function, and not for consequent function calls.

**Comment by d-e-s-o** [comment]
For my understanding, are we talking about `log` or `tracing` here?

**Comment by gahag** [comment]
About `log`. I have no experience with `tracing`.

**Comment by d-e-s-o** [comment]
I don't think `log` supports that in a proper way. By design, there is one program-global logger instance. It can be set once and there is no real mechanism for unsetting it. https://docs.rs/log/0.4.11/log/fn.set_logger.html

Given that it's program-global, even assuming you could unset it, you'd always end up with a racefest because tests are potentially run parallel by multiple threads. So the set/unset route is off the table.

As you said, one may be able to hack something together by filtering on certain records, but that is nothing that this crate aims to address.

The only other way I see is by making the `#[test]` attribute a wrapper around spawning a new process of the test and running the very test function (there is `--force-run-in-process` that is supported by test binaries and does something *similar*, but I don't run nightly and I doubt that it alone is sufficient). This way you should be able to get the desired behavior (and a bunch of other potentially nice properties) without additional hacks. Error reporting and general output will be lacking quite a bit, though, due to a lack of options to configure output of test binaries themselves (they always spit out their header/footer stuff).

Here is a quick and dirty prototype, but it would obviously go into a procedural macro:
```rust
#[test]
fn it_works() {
  fn inner() {
    assert_eq!(1 + 2, 2);
    println!("SUCCESS");
  }

  if std::env::var_os("__RECURSIVE_TEST_INVOCATION").is_none() {
    let exe = std::env::current_exe().unwrap();
    let out = std::process::Command::new(exe)
      .env("__RECURSIVE_TEST_INVOCATION", "")
      .arg("--test")
      .arg("--format=terse")
      .arg("--color=never")
      .arg("it_works")
      .output()
      .expect("failed to execute process");

    use std::io::Write as _;
    if out.status.success() {
      std::io::stdout().write(&out.stdout).unwrap();
    } else {
      // Proper error reporting isn't really possible. :-|
      panic!()
    }
  } else {
    inner()
  }
}
```

Once in a procedural macro, you could nest `#[test]` attributes as is already supported by `test-env-log`.

In any case, I don't think this functionality has a place in this very crate.

**Comment by gahag** [comment]
Well, that was quite informative. Thank you for taking your time into this issue. Hope we can have some improvement in the future in `log` regarding this matter.
